### ISSUE TITLE
[BUG] When going from spectating to joing a game, something weird happens

### ISSUE THREAD

**Issue by ManbearTagPro** [tagpro-game/tagpro-issues#176] opened 2015-03-15 20:30 UTC
This has happened a few times over the past few weeks, but not everytime. I join matchmaking for pubs and I join a game as a spectator. Someone in that game will quit, and I will automatically join the game I was spectating. But what happens when I join is I am still in spectator mode since I can zoom in and out with the +/- keys and scroll all over the map (but I can only view non-static game parts like balls and powerups in my viewport) while my ball seems to react to only some of my keypresses. It may have to do with some of the userscripts I have installed but I'm not sure (primarily the spectator center and move script found here: http://www.reddit.com/r/TagPro/comments/2rpbl2/userscripts_for_v3_check_inside_for_many_update/)

**Comment by I-mess-up** [comment] 2015-03-15 21:53
This is a known bug with some ball -1's spectator center and move script. When you have this issue, just refresh.

**Comment by SomeBall-1** [comment] 2015-03-19 23:39
I wish I could just test this out. I have a fix I'm pretty sure works but I haven't had this scenario happen to me in a while so I'm not completely sure. Maybe I'll just update the script anyway and hope that it fixes it.

**Comment by NewCompte** [comment] 2015-05-04 08:57
Closing this because it's not caused by us.

**Closed by NewCompte** 2015-05-04 08:57 UTC

**Comment by SomeBall-1** [comment] 2015-05-04 17:49
@NewCompte Can you confirm the socket behavior when getting moved from spectator to player in the same game? Is there a `"spectator"` socket event sent out that will update `tagpro.spectator` to `false`, or something similar?
