### ISSUE TITLE
[Bug] Spawn locations are not shown for the entire game if the game starts when the tab is not the active tab

### ISSUE THREAD

**Issue by RonSpawnson** [tagpro-game/tagpro-issues#90] opened 2015-01-12 06:23 UTC
Browsers tested: Chrome

**Steps to reproduce**
1. Start looking for a game
2. Switch to another tab
3. Wait until you hear the "Go" of the game starting.

**Expected behavior** 
The game should play normally

**Actual behavior**
Neither the friendly team or enemy team spawn shadows will show all game.

**Comment by NugaSausage** [comment] 2015-01-12 07:24
On a game-to-game basis, the lack of spawn shadows have been happening more and more frequently, and randomly too.

I have ZERO userscripts or extensions on, and I still face the issue.

**Comment by RonSpawnson** [comment] 2015-01-12 07:24
If you read my description, I don't think it is random. It is only if you start a game when on a different tab. Can you verify?

**Comment by memeganoob** [comment] 2015-01-12 07:28
For me, it's not 100% reproducible on chrome

It'll happen most of the time if the game starts in another tab, but it's also happened to me if the game starts in the open tab.

**Comment by RonSpawnson** [comment] 2015-01-12 07:30
Can you please elaborate on how it is not reproducible? Every time I execute the steps I menationed above in Chrome it leads to a game when I can't see any spawns. Are you indicating that you have joined a game while in another tab and were able to see spawns?

**Comment by RonSpawnson** [comment] 2015-01-12 07:37
Here is the stacktrace of the errors experienced when following the steps described in the initial comment: http://pastebin.com/4CVKqbbE

**Comment by RonSpawnson** [comment] 2015-01-12 07:43
Is this related to or caused by what someball -1 found with issue #86?

**Comment by SomeBall-1** [comment] 2015-01-12 08:59
@RonSpawnson Yes this is a duplicate of my issue, foreground layer isn't ready at the start. Apparently `tagpro.renderer.drawSpawn` stops getting called and no spawn shadows persists throughout the game. You can see the issue with [this script](http://pastebin.com/raw.php?i=JgsdTH0C) if you like. Very easily fixed, I'm sure they'll have it working by the time the next patch is pushed if it's not fixed already.

**Comment by NugaSausage** [comment] 2015-01-12 14:56
Woah I think you're right on the tab thing. Sorry for not reading; I though this was just the general complaint of spawn shadows.

Yeah I just tested it a bit, and looks like you're correct on this.

**Comment by I-mess-up** [comment] 2015-01-12 21:10
I’ve experienced this too.

**Comment by steppin** [comment] 2015-01-13 02:30
should be fixed with next push of patch

**Comment by steppin** [comment] 2015-01-21 23:29
Thanks for the reports.  This should be fixed.  Let us know if that's not the case!

**Closed** 2015-01-21 23:29 UTC
Labels: bug, fixed in testing
